# Generated by Django 4.2 on 2026-05-12 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='award', max_length=60)),
                ('threshold', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['threshold', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('topic', models.CharField(choices=[('loops', 'Loops'), ('arrays', 'Arrays'), ('oop', 'OOP'), ('algorithms', 'Algorithms')], max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('statement', models.TextField()),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('sample_input', models.TextField(blank=True)),
                ('sample_output', models.TextField(blank=True)),
                ('expected_output', models.TextField(help_text='Canonical output used for auto-checking.')),
                ('points', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['topic', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('php', 'PHP')], max_length=20)),
                ('code', models.TextField()),
                ('output', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer')], max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earners', to='problems.achievement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'status'], name='problems_su_student_2532b9_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', 'status'], name='problems_su_problem_7d1d02_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='problems_su_submitt_f08b6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('student', 'problem'), name='unique_accepted_submission_per_problem'),
        ),
        migrations.AlterUniqueTogether(
            name='studentachievement',
            unique_together={('student', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['topic', 'difficulty'], name='problems_pr_topic_22dea9_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_active'], name='problems_pr_is_acti_c99e79_idx'),
        ),
    ]
