# Generated by Django 4.2 on 2026-05-14 17:48

from django.db import migrations, models
import django.db.models.deletion


def create_initial_test_cases(apps, schema_editor):
    Problem = apps.get_model('problems', 'Problem')
    ProblemTestCase = apps.get_model('problems', 'ProblemTestCase')
    for problem in Problem.objects.all():
        if problem.expected_output and not ProblemTestCase.objects.filter(problem=problem).exists():
            ProblemTestCase.objects.create(
                problem=problem,
                label="Canonical expected output",
                input_data=problem.sample_input,
                expected_output=problem.expected_output,
                explanation="Created from the original expected output field.",
                order=1,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_status',
            field=models.CharField(choices=[('not_requested', 'Not requested'), ('unavailable', 'Unavailable'), ('passed', 'Passed'), ('needs_review', 'Needs review'), ('failed', 'Failed')], default='not_requested', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_test_results',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ProblemTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Test case', max_length=120)),
                ('input_data', models.TextField(blank=True)),
                ('expected_output', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(create_initial_test_cases, migrations.RunPython.noop),
    ]
