# Generated by Django 4.2 on 2026-05-12 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('solved_count', models.PositiveIntegerField(default=0)),
                ('attempted_count', models.PositiveIntegerField(default=0)),
                ('quiz_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='progresssnapshot',
            index=models.Index(fields=['date'], name='progress_pr_date_f7b5f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progresssnapshot',
            unique_together={('student', 'date')},
        ),
    ]
