# Generated by Django 4.2 on 2026-05-12 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=90)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['instructor__last_name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='section_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.section'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['is_active', 'code'], name='accounts_se_is_acti_4851a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('instructor', 'code')},
        ),
    ]
