# Generated by Django 4.2 on 2026-05-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_section_profile_section_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leaderboard_alias',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_quiz_percentage_on_leaderboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_real_name_on_leaderboard',
            field=models.BooleanField(default=False),
        ),
    ]
